# ESLint Configuration

# When true, eslint will stop its cascade with this file.
root: true

# Lists the environments where we expect JavaScript files to be executed. Eslint
# uses this informaton to understand what global variables should be available
# (e.g. `window` in a browser, `global` in Node.js, etc.).
env:
  es2022: true # sets ecmaVersion parser option automatically.
  browser: true
  node: true

# Lists the eslint configurations we're inheriting properties from.
extends:
  - 'plugin:react/recommended' # extends `eslint-plugin-react`
  - 'airbnb' # extends `eslint-config-airbnb`
  - 'prettier' # extends `eslint-config-prettier`

# Sets parser used by eslint. The babel parser allows eslint to parse additional
# js syntax supported by babel.
parser: '@babel/eslint-parser'

# Configures parser eslint uses to build an in-memory representation of each
# JavaScript file we want to lint.
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: 'module'

# Lists the of third-party plugins which extend eslint's capabilities.
plugins:
  - 'react' # adds `eslint-plugin-react`

# Plugins refer to the settings object which specifies information that should
# be shared by all of their rules.
settings:
  react:
    version: 'detect'

# Additional eslint rules.
rules:
  import/no-extraneous-dependencies:
    - 'error'
    - devDependencies: true
  react/jsx-props-no-spreading:
    - 'warn'
  react/no-unknown-property:
    - 'warn'
  react/require-default-props:
    - 'warn'
  react/forbid-prop-types:
    - 'error'
    - forbid: ['any', 'array']
  react/no-array-index-key:
    - 'warn'
overrides:
  - files: ['webpack.config.cjs']
    rules:
      no-nested-ternary:
        - 'warn'
