# Stylelint Configuration

# Lists the configurations we're inheriting properties from. Each successive
# config specified will take precedence over the previous.
extends:
  - 'stylelint-config-standard-scss'
  - 'stylelint-config-recess-order'
  - 'stylelint-config-prettier'
