#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# The commit-msg hook is called after entering a commit message and the only
# argument it receives is the file that contains said commit message.

# Runs commitlint, reading the commit message in the specified file. The --edit 
# flag tells commitlint to fallback to `COMMIT_EDITMSG` in the .git folder if no
# file is specified.
npx commitlint --verbose --edit ${1}
